# Generated by Django 5.0 on 2023-12-09 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'managed': False, 'ordering': ['id']},
        ),
    ]
